import uuid
import random
from datetime import datetime, timedelta

import psycopg2
from psycopg2.extras import execute_values
from faker import Faker


# Connection settings
HOST = 'localhost' # put your credentials here
USER = 'postgres' # put your credentials here
PASSWORD = 'admin123' # put your credentials here
DATABASE = 'opt_db' # put your credentials here
PORT = '5432' # put your credentials here

# Data volume settings
CINEMA_HALLS_COUNT = 10_000
CINEMA_MOVIES_COUNT = 100_000
CINEMA_TICKETS_COUNT = 1_000_000
CHUNK_SIZE = 50_000

fake = Faker()


def create_cinema_tables(cursor): # видаляю попередні таблиці з тесту та додаю совї нові
    print("Recreating database schema for cinema project...")
    cursor.execute("DROP TABLE IF EXISTS opt_orders, opt_products, opt_clients CASCADE;")
    cursor.execute("DROP TABLE IF EXISTS cinema_tickets, cinema_movies, cinema_halls CASCADE;")

    cursor.execute("""
        CREATE TABLE cinema_halls (
            hall_id UUID PRIMARY KEY,
            hall_name VARCHAR(255) NOT NULL,
            hall_type VARCHAR(50) NOT NULL CHECK (hall_type IN ('Standard', 'IMAX', 'VIP')),
            capacity INTEGER NOT NULL
        );
    """)
    cursor.execute("""
        CREATE TABLE cinema_movies (
            movie_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            movie_title VARCHAR(255) NOT NULL,
            movie_genre VARCHAR(100) NOT NULL,
            description TEXT
        );
    """)
    cursor.execute("""
        CREATE TABLE cinema_tickets (
            ticket_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            show_date TIMESTAMP NOT NULL,
            hall_id UUID REFERENCES cinema_halls(hall_id),
            movie_id INTEGER REFERENCES cinema_movies(movie_id)
        );
    """)


def insert_cinema_halls(cursor):
    print("Inserting into cinema_halls...")

    hall_insert_query = """
        INSERT INTO cinema_halls
            (hall_id, hall_name, hall_type, capacity)
        VALUES %s
    """

    hall_ids = []
    hall_types = ["Standard", "IMAX", "VIP"]

    for start in range(0, CINEMA_HALLS_COUNT, CHUNK_SIZE):
        current_chunk_size = min(CHUNK_SIZE, CINEMA_HALLS_COUNT - start)

        halls_data = []
        for _ in range(current_chunk_size):
            hall_id = str(uuid.uuid4())
            hall_ids.append(hall_id)

            halls_data.append(
                (
                    hall_id,
                    f"Hall №{fake.word().capitalize()}",
                    random.choice(hall_types),
                    random.choice([50, 100, 150, 300]),
                )
            )

        execute_values(cursor, hall_insert_query, halls_data)
        print(f"Inserted {start + current_chunk_size} rows into cinema_halls...")

    print("Inserted into cinema_halls.")
    return hall_ids


def insert_cinema_movies(cursor):
    print("Inserting into cinema_movies...")

    movie_insert_query = """
        INSERT INTO cinema_movies
            (movie_title, movie_genre, description)
        VALUES %s
        RETURNING movie_id
    """

    genres = ["Action", "Comedy", "Drama", "Sci-Fi", "Horror"]

    movies_data = [
        (
            f"The {fake.word().capitalize()} {fake.word().capitalize()}",
            random.choice(genres),
            fake.text(),
        )
        for _ in range(CINEMA_MOVIES_COUNT)
    ]

    execute_values(cursor, movie_insert_query, movies_data)

    movie_ids = [row[0] for row in cursor.fetchall()]

    print("Inserted into cinema_movies.")
    return movie_ids


def insert_cinema_tickets(cursor, hall_ids, movie_ids):
    print("Inserting into cinema_tickets...")

    ticket_insert_query = """
        INSERT INTO cinema_tickets
            (show_date, hall_id, movie_id)
        VALUES %s
    """

    show_date_start = datetime.now() - timedelta(days=365 * 2)

    for start in range(0, CINEMA_TICKETS_COUNT, CHUNK_SIZE):
        current_chunk_size = min(CHUNK_SIZE, CINEMA_TICKETS_COUNT - start)

        tickets_data = [
            (
                show_date_start + timedelta(days=random.randint(0, 365 * 2), hours=random.randint(0, 23)),
                random.choice(hall_ids),
                random.choice(movie_ids),
            )
            for _ in range(current_chunk_size)
        ]

        execute_values(cursor, ticket_insert_query, tickets_data)
        print(f"Inserted {start + current_chunk_size} rows into cinema_tickets...")

    print("Inserted into cinema_tickets.")


def main():
    connection = psycopg2.connect(
        host=HOST,
        user=USER,
        password=PASSWORD,
        dbname=DATABASE,
        port=PORT,
    )

    try:
        with connection:
            with connection.cursor() as cursor:
                create_cinema_tables(cursor)
                hall_ids = insert_cinema_halls(cursor)
                movie_ids = insert_cinema_movies(cursor)
                insert_cinema_tickets(cursor, hall_ids, movie_ids)

    finally:
        connection.close()


if __name__ == "__main__":
    main()
